# certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisecow-certificate
spec:
  secretName: wisecow-tls-secret
  dnsNames:
    - wisecow.local
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer

