apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: vijayalakshmi26/wisecow:latest
        ports:
        - containerPort: 4499
        readinessProbe:
          httpGet:
            path: /
            port: 4499
          initialDelaySeconds: 15   # give the app more time to start
          timeoutSeconds: 5         # allow slower responses
          periodSeconds: 10         # check every 10 seconds
          failureThreshold: 3       # fail only after 3 consecutive failures
          successThreshold: 1

