apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: vijayalakshmi26/wisecow:latest
        ports:
        - containerPort: 4499
        readinessProbe:
          httpGet:
            path: /
            port: 4499
          initialDelaySeconds: 30   # give the app more time to start
          timeoutSeconds: 5         # wait longer for response
          periodSeconds: 10         # check every 10 seconds
          failureThreshold: 6       # allow multiple failures before marking unready
          successThreshold: 1
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

