apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: vijayalakshmi26/wisecow:latest
        ports:
        - containerPort: 4499
        readinessProbe:
          tcpSocket:
            port: 4499
          initialDelaySeconds: 120   # give the app time to start
          periodSeconds: 10         # check every 10 seconds
          timeoutSeconds: 5         # wait for response
          failureThreshold: 12       # mark unready only after 6 failures
          successThreshold: 1
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

