apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  # Name used by the Certificate resource to reference this Issuer
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {} # This indicates a self-signed issuer
