name: Wisecow CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_IMAGE: vijayalakshmi26/wisecow
      MINIKUBE_HOME: ${{ github.workspace }}

    steps:
      # --- 1. Checkout repository ---
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- 2. Set up Docker Buildx ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # --- 3. Docker login ---
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: vijayalakshmi26
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- 4. Build and push Docker image ---
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile       # Make sure your real Dockerfile is in the repo root
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

      # --- 5. Install kubectl ---
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # --- 6. Install Minikube ---
      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

      # --- 7. Start Minikube and enable Ingress ---
      - name: Start Minikube
        run: |
          minikube start --driver=docker
          kubectl wait --for=condition=Ready node/minikube --timeout=5m
          minikube addons enable ingress

      # --- 8. Load Docker image into Minikube ---
      - name: Load Docker image into Minikube
        run: |
          minikube image load ${{ env.DOCKER_IMAGE }}:latest

      # --- 9. Install cert-manager ---
      - name: Install Cert-Manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.0/cert-manager.yaml
          kubectl wait --for=condition=Available deployment -n cert-manager --all --timeout=5m

      # --- 10. Deploy Wisecow manifests ---
      - name: Deploy Wisecow app
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f ingress.yaml
          kubectl apply -f issuer.yaml
          kubectl apply -f certificate.yaml

      # --- 11. Verify deployment ---
      - name: Verify deployment and test Ingress
        run: |
          kubectl get pods
          kubectl get svc
          kubectl get ingress
          kubectl get certificate

          INGRESS_IP=$(minikube ip)
          echo "Testing secure connection via Ingress on IP: $INGRESS_IP"
          curl -k --resolve wisecow.local:443:$INGRESS_IP https://wisecow.local

