name: CI/CD Minikube Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io curl conntrack
          sudo systemctl enable --now docker
          docker --version

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
          sudo dpkg -i minikube_latest_amd64.deb
          minikube version

      - name: Start Minikube
        run: |
          minikube start --driver=docker --kubernetes-version=v1.28.0
          minikube status

      - name: Load Docker image into Minikube
        run: |
          docker build -t myapp:latest .
          minikube image load myapp:latest

      - name: Enable Ingress
        run: minikube addons enable ingress

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f issuer.yaml
          kubectl apply -f certificate.yaml
          kubectl apply -f ingress.yaml

      - name: Update /etc/hosts for Minikube
        run: |
          IP=$(minikube ip)
          echo "$IP wisecow.local" | sudo tee -a /etc/hosts

      - name: Wait for Ingress and TLS
        run: |
          kubectl wait --for=condition=ready certificate/wisecow-cert --timeout=120s
          sleep 10

      - name: Test Wisecow
        run: |
          curl -k https://wisecow.local

