name: Wisecow CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget apt-transport-https ca-certificates software-properties-common conntrack

      - name: Install Docker
        run: |
          sudo apt-get remove -y docker docker-engine docker.io containerd runc
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl enable docker --now
          docker --version

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/
          minikube version

      - name: Start Minikube with supported Kubernetes
        run: |
          minikube start --driver=docker --kubernetes-version=v1.28.1
          minikube status

      - name: Enable Ingress addon
        run: |
          minikube addons enable ingress
          sleep 10

      - name: Load Docker image into Minikube
        run: |
          minikube image load vijayalakshmi26/wisecow:latest

      - name: Deploy Wisecow manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f ingress.yaml
          kubectl apply -f issuer.yaml
          kubectl apply -f certificate.yaml

      - name: Wait for pods to be ready
        run: |
          kubectl wait --for=condition=Ready pods --all --namespace=default --timeout=180s

      - name: Test Wisecow deployment
        run: |
          INGRESS_IP=$(minikube ip)
          echo "Ingress IP: $INGRESS_IP"
          curl -k --resolve wisecow.local:443:$INGRESS_IP https://wisecow.local

